name: Node.js CI

# on:
#   push:
#     tags:
#       - "**"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo ${{ toJson(github) }
      - run: echo ${{github.ref}}
      - run: echo ${{github.repository}}
      - run: echo ${{github.event_name}}
        if: contains(${{github.ref}}, 'tags')
      - run: yarn install
      - run: yarn build
